 # Navarra
def NavarraDB(archivo):
        import pandas as pd
        import numpy as np
        import xlrd 
        df = (pd.read_csv(archivo, skiprows=0)
                .dropna(how='all', axis=1))
        df.insert(0, 'ReferenciaCatastral', "") 
        second_column = df.pop('CP')
        df.insert(1, 'CP', second_column) 
        df.insert(2, 'CCAA', "Navarra") 
        df.insert(3, 'PROV', "Navarra") 
        df.insert(4, 'CMUN', "") 
        third_column = df.pop('Localidad')
        df.insert(5, 'Municipio', third_column) 
        df.insert(6, 'Coordenadas_latitud', "") 
        df.insert(7, 'Coordenadas_longitud', "") 
        df.insert(8, 'ZonaClimatica', "") 
        fifth_column = df.pop('_id')
        df.insert(9, 'NumeroCertificado', fifth_column) 
        df.insert(10, 'TipoEdificio', "") 
        seventh_column = df.pop('Tipo')
        df.insert(11, 'Edificio_existente_o_nuevo', seventh_column) 
        df.insert(12, 'FechaConstrucción', "") 
        df.insert(13, 'SuperficieUtil', "") 
        tenth_column = df.pop('Dirección')
        df.insert(14, 'Direccion', tenth_column) 
        eleventh_column = df.pop('ConsumoAnualAño')
        df.insert(15, 'Consumo_energía_primaria', eleventh_column) # Consumo_energía_primaria (kWh/m2año)
        eleventh_column = df.pop('CalificacionEnergética')
        df.insert(16, 'Calificación_consumo_energía', eleventh_column) 
        eleventh_column = df.pop('EmisionesCO2')
        df.insert(17, 'Emisiones_CO2', eleventh_column) # Emisiones CO2 (kgCO2/m2año)
        eleventh_column = df.pop('CalificacionEmisiones')
        df.insert(18, 'Calificación_emisiones', eleventh_column) 
        df.insert(19, 'Calificación_general_del_edificio', "") 
        df.insert(20, 'Emisiones_calefacción', "") 
        df.insert(21, 'Calificación_emisiones_calefacción', "") 
        df.insert(22, 'Consumo_calefacción', "") 
        df.insert(23, 'Calificación_consumo_calefacción', "") 
        df.insert(24, 'Emisiones_refrigeración', "") 
        df.insert(25, 'Calificación_emisiones_refrigeración', "") 
        df.insert(26, 'Consumo_refrigeración', "") 
        df.insert(27, 'Calificación_consumo_refrigeración', "") 
        df.insert(28, 'Emisiones_ACS', "") 
        df.insert(29, 'Calificación_emisiones_ACS', "") 
        df.insert(30, 'Consumo_ACS', "") 
        df.insert(31, 'Calificación_consumo_ACS', "") 
        df.insert(32, 'Emisiones_iluminación', "") 
        df.insert(33, 'Calificación_emisiones_iluminación', "") 
        df.insert(34, 'Consumo_iluminación', "") 
        df.insert(35, 'Calificación_consumo_iluminación', "") 
        df.insert(36, 'Normativa_edificación', "") 
        df.insert(37, 'Normativa_instalaciones', "") 
        eleventh_column = df.pop('Programa')
        df.insert(38, 'Programa_informático', eleventh_column) 
        df.insert(39, 'Fecha_registro', "") 
        df.insert(40, 'Dispone_de_solar_térmica',"") 
        df.insert(41, 'Dispone_de_solar_fotovoltaica', "") 
        df.insert(42, 'Dispone_de_geotérmica', "") 
        df.insert(43, 'Dispone_de_biomasa', "") 
        df.insert(44, 'Generador_instalación', "") 
        df.insert(45, 'Tipo_de_generador', "") 
        df.insert(46, 'Vector_energético', "") 
        return df
